from typing import Type, TypeVar
from slugify import slugify
from pathlib import Path
from pydantic import BaseModel
import yaml
from arkitekt_next.server.config import ArkitektServerConfig, Setup
from rich.console import Console

console = Console()

M = TypeVar("M", bound=BaseModel)


def safe_org_slug(name: str, max_length: int = 8) -> str:
    return slugify(
        name.lower(),
        separator="_",
        regex_pattern=r"[^a-z]+",  # ✅ allow only lowercase letters and underscores
    )[:max_length]


class YamlFile(BaseModel):
    """YAML file structure for configuration."""

    version: str
    setup: Setup


def _append_gitignore(directory: Path, filename: str) -> None:
    """Ensure ``filename`` is ignored (it holds generated secrets)."""
    gitignore_path = directory / ".gitignore"
    try:
        gitignore_content = gitignore_path.read_text()
    except FileNotFoundError:
        gitignore_content = ""

    if filename not in gitignore_content:
        with open(gitignore_path, "a") as f:
            f.write(f"\n{filename}\n")
            f.write("# Arkitekt server config file\n")
            f.write(
                "# This file is automatically generated and should not be modified manually.\n"
            )
            f.write(
                "# It contains sensitive information and should not be committed to version control.\n"
            )


def update_or_create_yaml_file(file_path: str, new_setup: Setup):
    """Update or create a YAML file with the given data."""
    with open(file_path, "w") as f:
        yaml_data = YamlFile(version="1.0", setup=new_setup)
        yaml.dump(yaml_data.model_dump(), f, default_flow_style=False)

    _append_gitignore(Path(file_path).parent, Path(file_path).name)


class ProfileFile(BaseModel):
    """On-disk wrapper for a deployment-profile config (hub / coord / hubinator).

    ``config`` is stored as a raw mapping so a single wrapper serves all three
    distinct profile schemas; the typed model is reconstructed on load by the
    caller-supplied model class.
    """

    version: str = "1.0"
    kind: str
    backend: str = "docker"
    config: dict


def write_profile_yaml(
    file_path: str,
    config_model: BaseModel,
    *,
    kind: str,
    backend: str = "docker",
) -> None:
    """Write a deployment-profile config to ``file_path`` under a versioned wrapper."""
    profile = ProfileFile(
        kind=kind, backend=backend, config=config_model.model_dump()
    )
    with open(file_path, "w") as f:
        yaml.dump(profile.model_dump(), f, default_flow_style=False)

    _append_gitignore(Path(file_path).parent, Path(file_path).name)


def load_profile_yaml(file_path: str, model_cls: Type[M]) -> tuple[M, str]:
    """Load a deployment-profile config, returning ``(config, backend)``.

    Raises ``FileNotFoundError`` if the file is missing.
    """
    try:
        with open(file_path, "r") as f:
            data = yaml.safe_load(f)
        return model_cls(**data["config"]), data.get("backend", "docker")
    except (FileNotFoundError, KeyError, TypeError):
        raise FileNotFoundError(
            f"Configuration file '{file_path}' not found or invalid. "
            "Run the matching `init` command first."
        )


def load_setup_file(file_path: str) -> Setup:
    """Load a YAML file and return the setup configuration."""
    try:
        with open(file_path, "r") as f:
            data = yaml.safe_load(f)
            return Setup(**data["setup"])
    except (FileNotFoundError, KeyError):
        raise FileNotFoundError(
            f"Configuration file '{file_path}' not found. Please run 'arkitekt init' to create a new configuration."
        )


def load_yaml_file(file_path: str) -> ArkitektServerConfig:
    """Load a YAML file and return the configuration."""
    try:
        with open(file_path, "r") as f:
            data = yaml.safe_load(f)
            return ArkitektServerConfig(**data["config"])
    except FileNotFoundError:
        raise FileNotFoundError(f"Configuration file '{file_path}' not found.")
    except yaml.YAMLError as e:
        raise ValueError(f"Error parsing YAML file: {e}")


def show_important_information(config: ArkitektServerConfig):
    """Display important information about the configuration."""
    console.print(f"Admin User: {config.global_admin}")
    console.print(f"Admin Password: {config.global_admin_password}")
