authentikate:
  issuers:
  - iss: go.arkitekt.live
    jwks_uri: https://go.arkitekt.live/.well-known/jwks.json
    kind: jwks_uri
  provenance:
    issuers:
    - iss: rekuest
      jwks_uri: http://rekuest:80/rekuest/.well-known/jwks.json
      kind: jwks_uri
  static_tokens: {}
django:
  admin:
    email: null
    password: uf2ao7tvs7yy2kpc54snsg5w29kju74plwhkp8wf
    username: admin
  csrf_trusted_origins:
  - http://localhost
  - https://localhost
  debug: false
  force_script_name: kabinet
  hosts:
  - '*'
  secret_key: '@$+9p*wefyta_7t&%0mss7)za)=sbq3@4qa3*2=h)x6rrfx3!z'
postgres:
  db_name: kabinet
  engine: django.db.backends.postgresql
  host: db
  password: 30ae0f6d873a75e6ca8d25f98033f849
  port: 5432
  username: sleepyviolettarsier
redis:
  host: redis
  port: 6379
