authentikate:
  issuers:
  - iss: go.arkitekt.live
    jwks_uri: https://go.arkitekt.live/.well-known/jwks.json
    kind: jwks_uri
  provenance:
    issuers:
    - iss: rekuest
      jwks_uri: http://rekuest:80/rekuest/.well-known/jwks.json
      kind: jwks_uri
  static_tokens: {}
datalayer:
  access_key: ioto0a8b46k97qy0he186cia71xa6tv6jwhxu8eu
  host: minio
  media:
    bucket: kraphmedia
  port: 9000
  protocol: http
  region: us-east-1
  secret_key: bpec0m7xg61z3rhc5eta8h62ieeplq8zopyi9goo
django:
  admin:
    email: null
    password: uf2ao7tvs7yy2kpc54snsg5w29kju74plwhkp8wf
    username: admin
  csrf_trusted_origins:
  - http://localhost
  - https://localhost
  debug: false
  force_script_name: kraph
  hosts:
  - '*'
  secret_key: +6k4@=za3q3gfyra7rejaq7nxpj!1jj+=!c0auo$^1csh-fgx0
postgres:
  db_name: kraph
  engine: django.db.backends.postgresql
  host: db
  password: 30ae0f6d873a75e6ca8d25f98033f849
  port: 5432
  username: sleepyviolettarsier
redis:
  host: redis
  port: 6379
