authentikate:
  issuers:
  - iss: go.arkitekt.live
    jwks_uri: https://go.arkitekt.live/.well-known/jwks.json
    kind: jwks_uri
  provenance:
    issuers:
    - iss: rekuest
      jwks_uri: http://rekuest:80/rekuest/.well-known/jwks.json
      kind: jwks_uri
  static_tokens: {}
django:
  admin:
    email: null
    password: d6vcd9a4i1adiovzvi7fkjk64yccq413ltkfgpm9
    username: admin
  csrf_trusted_origins:
  - http://localhost
  - https://localhost
  debug: false
  force_script_name: kabinet
  hosts:
  - '*'
  secret_key: '&%ryr-r3x@=6j2f=uy0a%bg2m9vgde=-405k@nsg&rh)g_=hdg'
postgres:
  db_name: kabinet
  engine: django.db.backends.postgresql
  host: db
  password: 30ae0f6d873a75e6ca8d25f98033f849
  port: 5432
  username: sleepyviolettarsier
redis:
  host: redis
  port: 6379
