buckets:
- name: rekuestmedia
- name: kabinetmedia
- name: mikromedia
- name: mikrozarr
- name: mikroparquet
- name: mikrobigfile
- name: flussmedia
- name: kraphmedia
users:
- access_key: 8izcp1tu5iaq3brecpdmhitixvjr4p48ny7cvz59
  name: Default User
  policies:
  - readwrite
  secret_key: rp72au4jmhyg9dd7hwslhunkf0xqm034vzy9uz0g
