name: Composability
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  mac_and_windows_unit:
    strategy:
      fail-fast: false
      matrix:
        extra: ["alpaka", "kraph", "mikro", "kabinet", "fluss", "reaktion", "lovekit", "rekuest", "unlok"]
        python-version: ["3.11"]
        poetry-version: [1.8]
        os: [macos-latest, windows-latest, linux]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Run Poetry Install
        run: poetry install --extras=${{matrix.extra}}
      - name: Install Qt because Qt sucks with Poetry
        run: poetry run pip install pyqt5 pyqtwebengine
      - name: Run Tests
        run: poetry run pytest --cov --cov-report=xml  -k "not cli"
  